export default {
   PLATE: require('../assets/images/plate.png'),
   DISCOVER: require('../assets/images/discover.png'),
   FAVORITE: require('../assets/images/favorite.png'),
   DELIVER: require('../assets/images/deliver.png'),
   FACEBOOK: require('../assets/images/facebook.png'),
   GOOGLE: require('../assets/images/google.png'),
   LOADING: require('../assets/images/loading.json'),
   FRIED_CHIECKEN: require('../assets/images/fried_chicken.png'),
   BURGER: require('../assets/images/burger.png'),
   PIZZA: require('../assets/images/pizza.png'),
   DESSERT: require('../assets/images/dessert.png'),
   DRINKS: require('../assets/images/drinks.png'),
   NOODLES: require('../assets/images/noodles.png'),
   DELIVERY_TIME: require('../assets/images/delivery_time.png'),
   DELIVERY_CHARGE: require('../assets/images/delivery_charge.png'),
   MARKER: require('../assets/images/marker.png'),
   EMPTY_CART: require('../assets/images/empty_cart.png'),
};
